//export const GetTopics = 'https://cnodejs.org/api/v1/topics'
// export const GetTopicDetail = 'https://cnodejs.org/api/v1/topic'
// export const GetUserDetail = 'https://cnodejs.org/api/v1/user'

 export const GetwareSearch = '/mobile/ware_search'
 export const GetBudget = '/mobile/get_budget'
 export const BasicShp = '/mobile/get_basic_shop'
 export const CreateUser = '/mobile/create_user'
 export const GetUser = '/mobile/get_user'
 export const SetBudget = '/mobile/set_budget'
 export const GetCpc = '/mobile/get_cpc'
 export const SetCpc = '/mobile/set_cpc'
 export const setItemsOnline = '/mobile/set_items_online'
 export const setItemsOffline = '/mobile/set_items_offline'
 export const getSaleData ='/mobile/get_sale_data'
 export const getHourlyCost = '/mobile/get_hourly_cost'
 export const getShopCampaginReport = '/mobile/get_shop_campaign_report'
